### ISSUE TITLE
support for `async` for node/jsdom testing

### ISSUE THREAD

**Issue by DanielSchaffer** [HichamBI/Angular-testing-webpack-mocha-chai-sinon#2]
I've used your configuration to set up testing for my library, which requires using an asynchronous `beforeEach` (using `async` from `@angular/core/testing`). While everything works great using the browser-based testing (e.g. running `npm run test:server`), when I try to run the headless testing (`npm run test`), it fails with the error `Error: Expected to be running in 'ProxyZone', but it was not found.`

You should be able to reproduce by simply wrapping the first `beforeEach` in your `book-form.component.spec.ts` in the `async` helper:

```
    beforeEach(async(() => {
        TestBed.configureTestingModule({
            imports: [FormsModule],
            declarations: [BookFormComponent],
        }).compileComponents();
    }));
```

I've tried a number of things to see if I could get it to work:
* Added `require('zone.js/dist/mocha-patch')` to the rest of the require statements in `mocha-node-test-shim.js` -> results in `window is not defined` error in `mocha-patch`.
* Moved `require('zone.js/dist/mocha-patch')` to after the JSDOM setup -> results in `Missing mocha.js` error in `mocha-patch`.
* Moved `require('zone.js/dist/mocha-patch')` to after JSDOM *and* TestBed setup -> same as previous
* Various other iterations of reordering the `require` statements and JSDOM setup, manually putting the `Mocha` object on the `global` and `global.window` objects all failed as well.

I know from reading the exchanges in [@angular/angular/11230](https://github.com/angular/angular/issues/11230) that you and others had been struggling with this issue, but I haven't been able to find a way to make it work. Any ideas?

**Comment by HichamBI** [comment]
Hi,

The **async()** function is used with **beforeEach** to compile components that have an external template or css files (with templateUrl or StylesUrls). But with **webpack** and his **angular2-template-loader**, templates and css files are inlined and we don't use XHR request to load them, so, **the async function is not needed.**

The async() function can also be used to tell the test framework that the current test is completed, like this example : 

```
 it('should do something after an async call', async(() => {
  fixture.detectChanges();

  fixture.whenStable().then(() => { // wait for async call
    fixture.detectChanges();        // update view
    expect(el.textContent).toBe(expected);
  });
}));
```

In this case, the **async()** function is only calling the Mocha (or Jasmine) **done()** function behind the scenes.
With Mocha, we call explicitly this function : 

```
 it('should do something after an async call', (done) => {
  fixture.detectChanges();

  fixture.whenStable().then(() => { // wait for async call
    fixture.detectChanges();        // update view
    expect(el.textContent).toBe(expected);
    done();
  });
});
```
 
The mocha-patch, is like the karma-patch, is used only for browser testing to get the right Zone.

For me this is not an issue, I'll close this thread.

Thanks for your comment, I hope that my answer can help you.
